name: Bug Report
description: 报告Bug.
title: "[Bug] "
labels: ["bug-report"]
body:
  - type: markdown
    attributes:
      value: |
        ## 注意
        每个Issue仅反馈一个问题
        标题尽可能包括关键信息
  - type: textarea
    id: what-happened
    attributes:
      label: 问题描述
      description: |
        在此描述问题:
        - 问题现象
        - 系统环境
        - 期待的结果
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 在此填入程序日志，如果有
      render: shell
  - type: checkboxes
    id: checking
    attributes:
      label: 在提交之前
      description: 你需要检查以下选项
      options:
        - label: 我确认这个Issue只提及了一个问题
          required: true
        - label: 我确认标题有意义，而不是如`Bug反馈`等类似的词
          required: true
